version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: sparkbytes
    environment:
      POSTGRES_USER: p_user
      POSTGRES_PASSWORD: p_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./example_users.csv:/docker-entrypoint-initdb.d/example_users.csv
      - ./example_events.csv:/docker-entrypoint-initdb.d/example_events.csv
volumes:
  postgres-data:
