#!/bin/bash

cd ./client || exit 1

skipBuild=false
if [[ $1 == "-s" ]]; then
	skipBuild=true
fi

if ! $skipBuild; then
	if ! npm install; then
		echo "Failed to install client dependencies"
		exit 1
	fi
	if ! npm run build; then
		echo "Failed to build client"
		exit 1
	fi
fi

cd .. || exit 1

echo "Checking for database docker container... (may prompt for password)"
dockerDb=$(docker ps | grep sparkbytes)
if [[ -z $dockerDb ]]; then
	echo "Starting database docker container..."
	sudo docker compose up -d
fi

cd ./api || exit 1

printf "\n#####################################################\n\n"

go run main.go
