#!/bin/bash

if [[ ! -e ./scripts ]]; then
  echo "ERR Could not find ./scripts directory, are you at the root of the repo? i.e. ~/repos/spark-bytes (correct) and not ~/repos/spark-bytes/scripts (bad)"
  exit 1
fi

mkdir -p ./build/logs

printf "Generating swagger docs..."
if ! swag init --pd -g server.go -d ./api/routes -q &>./build/logs/swag.log; then
  echo "FAILED"
  cat ./build/logs/swag.log
  echo "########## ^ Swag Init Logs ^ ##########"
  exit 1
fi
echo "DONE"
printf "########## END OF SWAG INIT ##########\n\n" >>./build/logs/swag.log

printf "Generating typescript api..."
if ! openapi-generator generate -i docs/swagger.json -g typescript-axios -o ./client/src/api/swag >>./build/logs/swag.log; then
  echo "FAILED"
  cat ./build/logs/swag.log
  echo "########## ^ Openapi Generator Logs ^ ##########"

  echo "openapi-generator (typescript) failed"
  exit 1
fi
echo "DONE"
